list: $/ukatz/quiz/models/category/columns.yaml
modelClass: Ukatz\Quiz\Models\Category
title: Category
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ukatz/quiz/category/update/:id'
